[package]
name = "labkv"
version = "0.1.0"
authors = ["root"]

[dependencies]
rand = "0.3.14"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
